# Triggers
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master    

# Jobs
jobs:
  # Build Job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: install node 16
        uses: actions/setup-node
        with:
          node-version: 16.x
      - name: install NPM dependencies
        run: npm install
      - name: Build Project
        run: nom run build
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist  

  # Deploy
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to gh pages
        uses: StanleyGemstone/FireQuiz-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          publish_dir: ./dist